### PR TITLE
Converting AMAS into a Python package

### PR DESCRIPTION
**Pull request by carlosp420**
You can register AMAS in the Python index (https://pypi.python.org/pypi) with:

``python setup.py register``

In this way, users will be able to install AMAS in their working environments
by using:

``python setup.py install``

You can upload a new version release to the Python index with:

``python setup.py sdist upload``

### CODE REVIEW

**Comment by marekborowiec** [comment]
Thanks again for your help Carlos, this is now published in PyPI.

**Comment by carlosp420** [comment]
nice. I see that AMAS is on the Python index but no code has been uploaded. <https://pypi.python.org/simple/amas/>

 Did you do the command? :
```shell
python setup.py sdist upload
```

**Comment by marekborowiec** [comment]
Woops! Take a look again.

**Comment by carlosp420** [comment]
great! I was able to install it with:

```shell
pip install amas
```
Now I can incorporated it in this project of mine: <https://github.com/carlosp420/VoSeq>

thanks!

**Pull request merged**
